/// An invitation link generated by a user to onboard a new peer.
class InviteModel {
  final String id;
  final String inviterId;
  final String code; // short alphanumeric code embedded in the link
  final String status; // pending | accepted | expired | revoked
  final DateTime createdAt;
  final DateTime expiresAt;

  const InviteModel({
    required this.id,
    required this.inviterId,
    required this.code,
    required this.status,
    required this.createdAt,
    required this.expiresAt,
  });

  factory InviteModel.fromJson(Map<String, dynamic> json) => InviteModel(
        id: json['id'] as String,
        inviterId: json['inviter_id'] as String,
        code: json['code'] as String,
        status: json['status'] as String,
        createdAt: DateTime.parse(json['created_at'] as String),
        expiresAt: DateTime.parse(json['expires_at'] as String),
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'inviter_id': inviterId,
        'code': code,
        'status': status,
        'created_at': createdAt.toIso8601String(),
        'expires_at': expiresAt.toIso8601String(),
      };

  bool get isActive =>
      status == 'pending' && expiresAt.isAfter(DateTime.now());

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is InviteModel && other.id == id;

  @override
  int get hashCode => id.hashCode;
}
